# 'throw' throws an error
# It takes 2 arguments, errortype and errormessage

# Examples

func def doubleIt
    if {cond {get _doubleIt_args 0} in [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]}
        return {cal {get _doubleIt_args 0}*2}
    else
        throw TypeError "Function 'doubleIt' only takes a number as an argument, got: {get _doubleIt_args 0}" 

cout {func doubleIt three}